### ISSUE TITLE
File Write/Read returning array of null bytes

### ISSUE THREAD

**Issue by ErikDombi** [sps014/FFmpegBlazor#10]
Been struggling to get this to work in my own local project, and I finally realized there is a demo of this project on netlify.
However the netlify instance of the project doesn't seem to be working either.

It seems either the File Write or File Read operation is broken. 
In my own testing, I found that writing and a file and reading it always returns an array of null bytes (00 00 00 00...). I assume it's working to some extent, as the file size remains exactly correct, but the actual content of the file is useless. 

Is this something wrong with ffmpeg.wasm? Or is this a FFmpegBlazor issue?

**Comment by ErikDombi** [comment]
If you're able to point me in the right direction, I can try to fix the issue in a pull request.

**Comment by sps014** [comment]
Hi, thanks for helping with it. 
Few things I that might require some testing are:
1. Write function unmarshalled Interop call C# and JS side : https://github.com/sps014/FFmpegBlazor/blob/b0588125fe1020886fed0bcc6c460b87e72b4313/FFmpegBlazor/FFMPEG.cs#L76
https://github.com/sps014/FFmpegBlazor/blob/b0588125fe1020886fed0bcc6c460b87e72b4313/FFmpegBlazor/wwwroot/blazorFfmpeg.js#L50

2. Similar there can be issue in read  function as well
https://github.com/sps014/FFmpegBlazor/blob/b0588125fe1020886fed0bcc6c460b87e72b4313/FFmpegBlazor/FFMPEG.cs#L54
https://github.com/sps014/FFmpegBlazor/blob/b0588125fe1020886fed0bcc6c460b87e72b4313/FFmpegBlazor/wwwroot/blazorFfmpeg.js#L33


API documentation for FFMPEG wasm Read can be found here:
[required doc](https://github.com/ffmpegwasm/ffmpeg.wasm/blob/master/docs/api.md#ffmpegfsmethod-args-any)

Blazor unmarshalled Interops
https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#unmarshalled-javascript-interop

if you find anything feel free to create PR.

**Comment by ErikDombi** [comment]
Seems like the following line isn't updating the byte array in FFMPEG.cs. 
https://github.com/sps014/FFmpegBlazor/blob/b0588125fe1020886fed0bcc6c460b87e72b4313/FFmpegBlazor/wwwroot/blazorFfmpeg.js#L47

I don't know enough about how Blazor handles array pointers or how chrome shares memory, but I have a sneaking suspicion that this is an issue with SharedArrayBuffer. The fact that the demo broke without any changes except browser version further supports this theory.

**Comment by sps014** [comment]
Not entirely sure but one of possible reason could be [this](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/byte-array-interop) breaking change.

**Comment by sps014** [comment]
Hi, i am able to fix the issue, there was a breaking change in [Blazor array interop](https://docs.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/6.0/byte-array-interop).

We do longer need to deal with raw buffer pointers manually.

In `blazorffmpeg.Js` we can have our new js interop codefor readFileProcess as
```js

        readFileProcess: (h)=>
        {
            return readFileBuffers[h];
        },
 ```
 and in FFMPEG.cs we can directly invoke 
 ```cs
        public async Task<byte[]> ReadFile(string path)
        {
            _ = reference.InvokeUnmarshalled<FileConf, bool>("readFileFFmpeg", new FileConf()
            {
                Hash = Hash,
                Path = path
            });
           
            await Task.Delay(5);
            
            var array =reference.Invoke<byte[]>("readFileProcess",Hash);
            return array;
        }
        
```
you can still send PR with these changes if you want.
thanks.
