### ISSUE TITLE
Is there a way to catch errors/exceptions coming from the ff.Run()?

### ISSUE THREAD

**Issue by WarrickWilson** [sps014/FFmpegBlazor#12]
I'm doing a two-pass conversion on an MP4 to AVI. If it works, things seems great. But if my parameters will not allow a file to be created, I get an error that I can sort of see with logging messages, but I get an immediate RuntimeError: memory access out of bounds right after that. I'm running locally in a "Start without Debugging" mode. I'm not sure if it's something I'm doing, or if it's something happening in the code with this approach. Any ideas?

![FFMpegBlazor_error_low_bitrate_with_exception](https://user-images.githubusercontent.com/84544643/176570752-0d06fce4-93aa-4213-86fb-f05ce522d21a.png)

**Comment by sps014** [comment]
Hi, thanks for reporting this issue,
If possible can you share the code so I could reproduce on my end. Generally speaking there is a way to catch these errors, I had implemented for Calling Async js function in [BlazorBindGen](https://github.com/sps014/BlazorBindGen)

**Comment by sps014** [comment]
For quick fix :
1. You can reference lib directly, 
2. And you can wrap          https://github.com/sps014/FFmpegBlazor/blob/7bc3fde9da68e34b7cbad4316e4915b222871c7f/FFmpegBlazor/wwwroot/blazorFfmpeg.js#L31
 in try catch block 
3.  send js exception to c# (if you want).

This weekend I will fix and publish on nuget.

**Comment by sps014** [comment]
I am rewriting FFMPEG with [BlazorBindGen](https://github.com/sps014/BlazorBindGen) which can catch exception from JS process and redirect it to C# process. It may take time as  Blazor threads are coming in few releases so waiting for it also.

**Comment by sps014** [comment]
Most of FFmpeg wasm exceptions are now catchable with https://github.com/sps014/FFmpegBlazor/commit/efb02a53476b7105b1c763f7fbfa73be47bb0740 commit.
