### ISSUE TITLE
[Bug] IJSUnmarshalledRuntime is obsolote in .NET 7

### ISSUE THREAD

**Issue by Ksdmg** [sps014/FFmpegBlazor#14]
I have a .NET 7 project running blazor server side.
When initializing the JSRuntime, an exception is thrown:

```
await FFmpegFactory.Init(Runtime); // throws System.InvalidCastException: 'Unable to cast object of type 'Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime' to type 'Microsoft.JSInterop.IJSUnmarshalledRuntime'.'
```

I found this -> https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/javascript-interoperability/import-export-interop.md#obsolete-javascript-interop-api

**Comment by sps014** [comment]
Thanks for reporting this issue, I will be refactoring the interop code this weekend.

**Comment by BigBang1112** [comment]
It also seems to be completely removed in .NET 9.

**Comment by sps014** [comment]
I will mostly rewrite the current js interop code after .NET 9 RC2 release, hopefully they have some news regarding .net wasm threads.

**Comment by BigBang1112** [comment]
I've been roughly following where the new Blazor goes and I think they delayed multithreading once again (like they delay half of the features as usual), and looking deeper it is indeed the reality: https://github.com/dotnet/aspnetcore/issues/17730#issuecomment-2059602250

**Comment by sps014** [comment]
Closing this as I have removed IJSUnmarshalled API from source.
