### ISSUE TITLE
Factory loads relative path resulting in 404s

### ISSUE THREAD

**Issue by dutchaussie** [sps014/FFmpegBlazor#17]
I am calling the FFMpegBlazor from within my application: I am at the url: myapp.com/video/asset/3016.
When the factor proceeds to load ffmpeg-core.js for example: this is the url that gets used: 

https://localhost:44348/video/3016/_content/FFmpegBlazor/0.10.0/dist/ffmpeg-core.js resulting in a 404.

In the factory class it is using a relative path:    //cdnURL ??= "https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js";
            cdnURL = "./_content/FFmpegBlazor/0.10.0/ffmpeg.min.js";
            await Runtime.InvokeVoidAsync("import", cdnURL);
            await Runtime.InvokeVoidAsync("import", "./_content/FFmpegBlazor/blazorFfmpeg.js");  

It should be using an absolute path:  cdnURL = "/_content/FFmpegBlazor/0.10.0/ffmpeg.min.js";

the _content folder is at the root of the application and that is where the build places the needed js files.

**Comment by sps014** [comment]
Hello @dutchaussie thanks for reporting it, 
would you like to submit PR for it?

**Comment by sps014** [comment]
Fixed with v1.0.0.9
