### ISSUE TITLE
How to load the first frame of video and export it as jpg

### ISSUE THREAD

**Issue by wisamidris7** [sps014/FFmpegBlazor#18]
I need to grab the first frame from video and export it as jpg or png and I didn't understand how to export a jpg form video.
Help wanted

**Comment by sps014** [comment]
simple Ffmpeg command is
`ffmpeg -i input.mp4 -frames:v 1 output.jpg`

but with FfmpegWasm we can do same by following [example ](https://github.com/sps014/FFmpegBlazor?tab=readme-ov-file#sample), do few changes like this

1. Load FfmpegBlazor
2. Load mp4 file 
3. Write mp4 file to ffmpeg wasm file system eg. "myFile.mp4"
4. run ffmpeg command  by
```cs
            await ff.Run("-i", "myFile.mp4", "-frames:v","1","output.jpg");
```
5. read output.jpg  url and show
            url2 = FFmpegFactory.CreateURLFromBuffer(res, "output.jpg", "image/jpg");
```
