### ISSUE TITLE
CORS fails on Firefox

### ISSUE THREAD

**Issue by NeoCoderMatrix86** [sps014/FFmpegBlazor#6]
On Firefox I can not use the library because of bad CORS:

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://unpkg.com/@ffmpeg/ffmpeg@0.9.7/dist/ffmpeg.min.js. (Grund: CORS-Anfrage schlug fehl).

Modul-Quell-URI ist in diesem Dokument nicht erlaubt: "https://unpkg.com/@ffmpeg/ffmpeg@0.9.7/dist/ffmpeg.min.js".

How can this be fixed?

**Comment by sps014** [comment]
Hi, 
I tested  my sample site on Firefox,  `SharedArrayBuffer` was main cultprit.
It turns out that  the base Repo [FFmpeg Wasm Sample](https://codepen.io/jeromewu/pen/NWWaMeY) had the same issue.

Can you please report [there](https://github.com/ffmpegwasm/ffmpeg.wasm).
If it will be fixed there, it won't take long for me to fix it here as well.
Currently only Chromium doesn't enforce `SharedArrayBuffer` CORS header  restriction , however this will also change in future.
The original issue is [here](https://github.com/ffmpegwasm/ffmpeg.wasm/issues/102).

**Comment by NeoCoderMatrix86** [comment]
Thanks for your investigation. I opened up https://github.com/ffmpegwasm/ffmpeg.wasm/issues/166

In Blazor assemblies it is common that you include all javascript required in wwwroot, why not just use this?

**Comment by sps014** [comment]
Great suggestion,
I will definitely explore self host option in upcoming releases.

**Comment by NeoCoderMatrix86** [comment]
Just for your information: https://github.com/ffmpegwasm/ffmpeg.wasm is an experimental project. The CORS problem will be much greater in May, because Chrome (and therefore Edge because it is build on top of it) will drop support for SharedArrayBuffer. Having this in mind, I dropped this library out of my project in short term and will have a look for anther solution (production stable) in long term. As mentioned here https://github.com/ffmpegwasm/ffmpeg.wasm/issues/166#issuecomment-795528297 maybe you can have a version with ffmpeg.js.

**Comment by sps014** [comment]
I don't think `sharedArrayBuffer` will be dropped any time soon , [Blazor folks](https://github.com/dotnet/aspnetcore/issues/17730#issuecomment-717573287) are using sharedArrayBuffer to implement multi threading in WASM.
I am experimenting in this [branch](https://github.com/sps014/FFmpegBlazor/tree/Self-Host).
Here is good article by  [Uno team](https://platform.uno/blog/the-state-of-webassembly-2020-and-2021/) explaining the changes in WASM in 2021.

**Comment by sps014** [comment]
Hey [Netlify](https://docs.netlify.com/routing/headers/) allows adding custom headers ,
Netlify is free , similar to Github pages. 

Steps:
1. build this branch (https://github.com/sps014/FFmpegBlazor/tree/Self-Host).
2. add reference of ffmpeg library to your project
3. publish to netlify
4. add custom [header](https://docs.netlify.com/routing/headers/) 
`Header set Cross-Origin-Opener-Policy: same-origin`
`Header set Cross-Origin-Embedder-Policy: require-corp`
 to wasm route https://yourpage.com/_content/FFmpegBlazor/0.8.5/dist/ffmpeg-core.wasm
replace yourpage.com to your netlify app address

**Comment by NeoCoderMatrix86** [comment]
Well, I'm currently not planning to move to Netlify. Maybe in future, but currently I'm facing to much bugs and need to fix them first. If the library works on all major browsers, I will defently use it, but currently it is to unstable for my approach. I will come here later and see how the next version performs :).

**Comment by Aloento** [comment]
This problem is even more significant today and I think it should be depreciated `ffmpeg.wasm`.
