### ISSUE TITLE
Support network stream

### ISSUE THREAD

**Issue by ChengYen-Tang** [sps014/FFmpegBlazor#8]
Can this support network streaming?  like rtmp, rtsp

**Comment by sps014** [comment]
Hi,
FfmpegBlazor is based of ffmpeg.wasm which currently doesn't support rtmp or rtsp as stated in https://github.com/ffmpegwasm/ffmpeg.wasm/issues/67#issuecomment-721452717

**Comment by ChengYen-Tang** [comment]
Ok, thank you.
