### ISSUE TITLE
JSException: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by nor0x** [sps014/FFmpegBlazor#9]
i'm not sure if it's somehow related with #6 but there i get the following error if i want to use FFmpegBlazor in my WebAssembly project. I noticed that there is a `JSException` on the hosted version on netlify as well.
i'm testing https://ffmpegblazor.netlify.app/tomp3

```
Microsoft.JSInterop.JSException: SharedArrayBuffer is not defined
ReferenceError: SharedArrayBuffer is not defined
    at blob:https://localhost:5011/8b279815-9592-46f1-806c-a92e17d96ca7:22:175
    at https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js:1:7334
    at f (https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js:1:12320)
    at Generator._invoke (https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js:1:12108)
    at Generator.next (https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js:1:12745)
    at i (https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js:1:5052)
    at c (https://unpkg.com/@ffmpeg/ffmpeg@0.10.0/dist/ffmpeg.min.js:1:5255)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at FFmpegBlazor.FFMPEG.Load(Boolean triggerEvents)
```

i'm happy to provide more info if needed.
Thank you

**Comment by sps014** [comment]
Thanks for info.
Recently chromium browsers stopped supporting `SharedArrayBuffer` on cross origin sites (since i was fetching .wasm from different domain). That means I have to ship `ffmpeg.wasm` with our application. eg. https://github.com/sps014/FFmpegBlazor/tree/Self-Host . 
Also we need to set
 ```
Cross-Origin-Embedder-Policy: require-corp<br>
Cross-Origin-Opener-Policy: same-origin
```
headers. 
Will update site this weekend. 
These extra steps will be removed in .NET 7 when Multithreading arrives. Waiting for that preview to hit, we will have option to further speedup video processing and trim application.
have a great day.

**Comment by nor0x** [comment]
thank you very much for you quick reply 👏
i will check the self-host branch and see how i can implement it for my usecase

**Comment by aokocax** [comment]
Those who want to test it quickly on their local computer can add a web.config file to their project and run the project with IISExpress.
![image](https://user-images.githubusercontent.com/1059475/156922277-ff39bf6c-b4a7-4437-b8a2-aae85c11ccb4.png)


<?xml version="1.0" encoding="utf-8"?>
<configuration>


  For more info see https://go.microsoft.com/fwlink/?linkid=838655 -->
  
	<system.webServer>
		<httpProtocol>
			<customHeaders>
	
				<add name="Cross-Origin-Embedder-Policy" value="require-corp"/>
				<add name="Cross-Origin-Opener-Policy" value="same-origin"/>
				

			</customHeaders>
		</httpProtocol>
	</system.webServer>
</configuration>

**Comment by sps014** [comment]
@aokocax thank you so much, this will help me so much, i asked the same question on aspnetcore  https://github.com/dotnet/aspnetcore/issues/38327 unfortunately was not able to find any pointers in  the same direction..

**Comment by aokocax** [comment]
You're welcome, I thank you too for the beautiful project.
> @aokocax thank you so much, this will help me so much, i asked the same question on aspnetcore [dotnet/aspnetcore#38327](https://github.com/dotnet/aspnetcore/issues/38327) unfortunately was not able to find any pointers in the same direction..

**Comment by sps014** [comment]
@nor0x Website is now fixed and you can check netlify deployment example here
https://ffmpegblazor.netlify.app/
Thanks for notifying.

**Comment by nor0x** [comment]
thank you both 🙌
closing the issue now!

**Comment by nor0x** [comment]
> Those who want to test it quickly on their local computer can add a web.config file to their project and run the project with IISExpress. ![image](https://user-images.githubusercontent.com/1059475/156922277-ff39bf6c-b4a7-4437-b8a2-aae85c11ccb4.png)
> 
> `<?xml version="1.0" encoding="utf-8"?>` `<configuration>` ` <system.webServer>` ` <httpProtocol>` ` <customHeaders>`
> 
> ` <add name="Cross-Origin-Embedder-Policy" value="require-corp"/>` ` <add name="Cross-Origin-Opener-Policy" value="same-origin"/>`
> 
> ` </customHeaders>` ` </httpProtocol>` ` </system.webServer>` `</configuration>`

thanks for the suggestion @aokocax ! do you know how to configure this with Kestrel? I'm on macOS and cannot use IIS for local development

**Comment by sps014** [comment]
That should be resolved in .NET 7 when they deliver Multi threading support in blazor wasm .
Currently not sure about Kestrel , didn't find anything useful.

**Comment by Heartnett** [comment]
Is there a workaround for vscode?

**Comment by sps014** [comment]
It is blocked by: https://github.com/dotnet/aspnetcore/issues/38327
Currently only IIS allows us to add these two headers , running from VSCode require a lot of [steps](https://medium.com/volosoft/running-asp-net-core-web-app-on-iis-express-from-command-line-558530a5dd07). These steps should be reduced in upcoming few .NET  7 preview (it is really close). In the mean time I suggest to use VS  for better developer experience.

**Comment by Heartnett** [comment]
I'm running vscode on linux, VS is a non-starter for me.

**Comment by sps014** [comment]
@Heartnett 
Another alternative is to build project then use 3rd party web server which can serve wasm files and allows you to add headers with web requiest ie. add these :
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

**Comment by marcusvfcarvalho** [comment]
Was this issue fixed? By the comments it should be fixed in net 7 but I still have the error.

**Comment by timothyparez** [comment]
This does not appear to be fixed in .net 7

**Comment by keke1210** [comment]
.NET 8 is here and this issue is only resolved in preview.
